---
kind: pipeline
name: Pre-Flight

steps:
  - name: yamllint
    image: cytopia/yamllint
    commands: 
      - yamllint --version
      - yamllint .

---
kind: pipeline
name: Home Assistant

depends_on: 
  - Pre-Flight

steps:
  - name: "Config Check: Beta"
    image: homeassistant/home-assistant:beta
    pull: always
    failure: ignore
    commands:
      - cd /usr/src/homeassistant
      - "python -m homeassistant -c /drone/src/hass/settings \
         --script check_config"

  - name: "Config Check: RC"
    image: homeassistant/home-assistant:rc
    pull: always
    failure: ignore
    commands:
      - cd /usr/src/homeassistant
      - "python -m homeassistant -c /drone/src/hass/settings \
        --script check_config"

  - name: "Config Check: Latest"
    image: homeassistant/home-assistant:latest
    pull: always
    commands:
      - cd /usr/src/homeassistant
      - "python -m homeassistant -c /drone/src/hass/settings \
        --script check_config"
