---
kind: pipeline
name: Pre-Flight

steps:
  - name: yamllint
    image: cytopia/yamllint
    commands: 
      - yamllint --version
      - yamllint .

  - name: ShellCheck
    image: koalaman/shellcheck-alpine:stable
    failure: ignore
    commands:
      - shellcheck --version
      - shellcheck scripts/*.sh

  - name: markdownline
    image: pipelinecomponents/markdownlint:latest
    commands:
      - mdl --style all --warnings ./README.md

---
kind: pipeline
name: Home Assistant

depends_on: 
  - Pre-Flight

steps:
  - name: "Config Check: Beta"
    image: homeassistant/home-assistant:beta
    pull: always
    failure: ignore
    commands:
      - python -m homeassistant --version
      - cp ./.stubs/secrets.yaml ./
      - mkdir -p /config/www/snapshots
      - mkdir -p /config/www/security
      - mkdir -p /config/www/snapshots/platerecognizer
      - "python -m homeassistant --config ./ \
         --script check_config \
         --info all"

  - name: "Config Check: RC"
    image: homeassistant/home-assistant:rc
    pull: always
    failure: ignore
    commands:
      - python -m homeassistant --version
      - cp ./.stubs/secrets.yaml ./
      - mkdir -p /config/www/snapshots
      - mkdir -p /config/www/security
      - mkdir -p /config/www/snapshots/platerecognizer
      - "python -m homeassistant --config ./ \
         --script check_config \
         --info all"

  - name: "Config Check: Latest"
    image: homeassistant/home-assistant:latest
    pull: always
    commands:
      - python -m homeassistant --version
      - cp ./.stubs/secrets.yaml ./
      - mkdir -p /config/www/snapshots
      - mkdir -p /config/www/security
      - mkdir -p /config/www/snapshots/platerecognizer
      - "python -m homeassistant --config ./ \
         --script check_config \
         --info all"

---
kind: pipeline
name: Notification

depends_on: 
  - Pre-Flight
  - Home Assistant

steps:
  - name: telegram-notification
    image: appleboy/drone-telegram
    settings:
      token:
        from_secret: telegram_token
      to:
        from_secret: telegram_to

trigger:
  status:
    - success
    - failure