- id: Start_Up_Home_Assistant
  alias: Start Up Home Assistant
  trigger:
  - platform: homeassistant
    event: start
  action:
  - service: script.turn_on
    entity_id: script.start_up_home_assistant
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  trigger:
  - platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data_template:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      shellyswitch25-00C928-relay-0: light
      shellyswitch25-00C928-relay-1: light
      shelly1-2C6E97-relay-0: light
- alias: Update Last Motion
  id: Update Last Motion
  initial_state: 'on'
  trigger:
  - platform: state
    entity_id:
    - binary_sensor.bureau_motion
    - binary_sensor.speelkamer_motion
    - binary_sensor.motion_achterdeur
    - binary_sensor.oprit_camera
    - binary_sensor.voor_deur
    - binary_sensor.achter_deur
    - binary_sensor.keuken_deur
    - binary_sensor.garage_deur
    - binary_sensor.motion_wc_boven
    - binary_sensor.motion_wc_beneden
    - binary_sensor.motion_gang_eerste_2
    - binary_sensor.motion_gang_eerste_1
    - binary_sensor.motion_inkom
    - binary_sensor.motion_gang_zolder
    - binary_sensor.motion_voordeur
    - binary_sensor.motion_bureau
    - binary_sensor.motion_logeerkamer
    - binary_sensor.motion_speelkamer
    - binary_sensor.motion_living
    to: 'on'
  action:
    service: variable.set_variable
    data:
      variable: last_motion
      attributes_template: "{\n      \"history_1\": \"{{ variable.state }}\",\n  \
        \    \"history_2\": \"{{ variable.attributes.history_1 }}\",\n      \"history_3\"\
        : \"{{ variable.attributes.history_2 }}\",\n      \"history_4\": \"{{ variable.attributes.history_3\
        \ }}\",\n      \"history_5\": \"{{ variable.attributes.history_4 }}\",\n \
        \     \"history_6\": \"{{ variable.attributes.history_5 }}\",\n      \"history_7\"\
        : \"{{ variable.attributes.history_6 }}\",\n      \"history_8\": \"{{ variable.attributes.history_7\
        \ }}\",\n      \"history_9\": \"{{ variable.attributes.history_8 }}\",\n \
        \     \"history_10\": \"{{ variable.attributes.history_9 }}\"\n}\n"
    data_template:
      value: '{{ trigger.to_state.attributes.friendly_name|replace(''motion sensor'','''')
        }}: {{as_timestamp(states.variable.last_motion.last_changed)| timestamp_custom(''%X'')
        }}

        '
- id: '1575277594428'
  alias: Set night profile for oprit camera
  description: ''
  trigger:
  - event: sunset
    platform: sun
  condition: []
  action:
  - service: shell_command.set_oprit_profile_night
- id: '1575277627609'
  alias: Set day profile for oprit camera
  description: ''
  trigger:
  - event: sunrise
    platform: sun
  condition: []
  action:
  - service: shell_command.set_oprit_profile_day
