- platform: template
  sensors:
    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.philippe", "home")
            and not is_state("person.isabel", "home") }}
    guest_mode:
      value_template: "{{ is_state('input_boolean.guest_mode','on') }}"
      device_class: presence
      friendly_name: "Guest Mode"
    night_mode:
      value_template: "{{ is_state('input_boolean.night_mode', 'on') }}"
      device_class: moving
      friendly_name: "Night Mode"
    home_proximity:
       value_template: >-
               {% if (states.proximity.philippe_home.attributes.dir_of_travel == "towards" and states.proximity.philippe_home.state | int <= 2) or
                     (states.proximity.isabel_home.attributes.dir_of_travel == "towards" and states.proximity.isabel_home.state | int <= 2) %}
                  True
               {%else%}
                  False
               {%endif%}

- platform: mqtt
  name: "Oprit Camera"
  state_topic: "zoneminder/1"
  payload_on: "event_start"
  payload_off: "event_end"
  device_class: "motion"
  json_attributes_topic: "zoneminder/1"
  json_attributes_template: "{{ value_json | tojson }}"
  value_template: "{{ value_json.eventtype}}"
  
- platform: mqtt
  name: "Weather Station Rain"
  state_topic: "stat/weather_station/RAIN"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "moisture"

- platform: zoneminder
