- platform: template
  sensors:
    no_one_home:
      friendly_name: No one is home
      value_template: >
        {{ not is_state("person.philippe", "home")
            and not is_state("person.isabel", "home") }}
    motion_detected_indoor:
      friendly_name: Any indoor motion detected
      value_template: >
        {{ is_state("binary_sensor.motion_wc_boven", "on")
            or is_state("binary_sensor.motion_wc_beneden", "on")
            or is_state("binary_sensor.motion_gang_eerste_2", "on")
            or is_state("binary_sensor.motion_gang_eerste_1", "on")
            or is_state("binary_sensor.motion_inkom_1", "on")
            or is_state("binary_sensor.motion_inkom_2", "on")
            or is_state("binary_sensor.motion_gang_zolder", "on")
            or is_state("binary_sensor.motion_bureau", "on")
            or is_state("binary_sensor.motion_dressing", "on")
            or is_state("binary_sensor.motion_speelkamer", "on")
            or is_state("binary_sensor.motion_living", "on") }}
    motion_detected_indoor_in_last_hour:
      friendly_name: Any indoor motion detected in last hour
      value_template: >
        {{ is_state("binary_sensor.motion_detected_indoor", "on") }}
      delay_off: "01:00:00"
    motion_detected_bureau_in_last_hour:
      friendly_name: Any motion detected (bureau) in last hour
      value_template: >
        {{ is_state("binary_sensor.motion_bureau", "on") }}
      delay_off: "01:00:00"
    guest_mode:
      value_template: "{{ is_state('input_boolean.guest_mode','on') }}"
      device_class: presence
      friendly_name: "Guest Mode"
    night_mode:
      value_template: "{{ is_state('input_boolean.night_mode', 'on') }}"
      device_class: moving
      friendly_name: "Night Mode"
    home_proximity:
      value_template: >-
        {{ (is_state_attr('proximity.philippe_home','dir_of_travel','towards') and states('proximity.philippe_home') | int <= 2) or
          (is_state_attr('proximity.isabel_home','dir_of_travel','towards') and states('proximity.isabel_home') | int <= 2)}}
    motion_inkom:
      friendly_name: Inkom
      value_template: >
        {{ is_state("binary_sensor.motion_inkom_1", "on") or is_state("binary_sensor.motion_inkom_2", "on")}}
      device_class: motion
    motion_gang_eerste:
      friendly_name: Gang Eerste
      value_template: >
        {{ is_state("binary_sensor.motion_gang_eerste_1", "on") or is_state("binary_sensor.motion_gang_eerste_2", "on")}}
      device_class: motion

#- platform: mqtt
#  name: "Oprit Camera"
#  state_topic: "zoneminder/1"
#  payload_on: "event_start"
#  payload_off: "event_end"
#  device_class: "motion"
#  json_attributes_topic: "zoneminder/1"
#  json_attributes_template: "{{ value_json | tojson }}"
#  value_template: "{{ value_json.eventtype}}"
  
- platform: mqtt
  name: "Weather Station Rain"
  state_topic: "stat/weather_station/RAIN"
  payload_on: "ON"
  payload_off: "OFF"
  device_class: "moisture"

#- platform: zoneminder

- platform: workday
  country: BE

- platform: template
  sensors:
    oprit_motion:
      friendly_name: "Oprit Motion"
      value_template: '{{ is_state(''input_boolean.oprit_motion'', ''on'') }}'
      device_class: motion
    oprit_known_plate:
      friendly_name: "Oprit Known Plate"
      value_template: !secret known_car_plate_template

- platform: mqtt
  name: "Oprit CCTV Motion"
  state_topic: "cctv/oprit/motion"
  device_class: motion
  json_attributes_topic: "cctv/oprit/motion"
  value_template: '{{ value_json.motion }}'
  payload_off: "off"
  payload_on: "on"