# - platform: zoneminder

- platform: mjpeg
  mjpeg_url: http://192.168.0.207:8081
  still_image_url: http://192.168.0.207:8765/picture/1/current/
  name: Oprit

- platform: generic
  name: Doods Oprit
  still_image_url: http://192.168.0.104:8123/local/snapshots/oprit_latest.jpg