homeassistant:
  media_dirs:
    media: /media
    snapshots: /config/www/snapshots
    security: /config/www/security
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - fd00::/8
  external_url: !secret external_url

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.201
    - 192.168.0.21

logger:
  default: warning                  # don't use debug

  logs:
    #custom_components.evohome_cc: warn
    #ramses_rf.message: info
    #ramses_rf.protocol.message: info
    fritzconnection: info

# Text to speech
tts:
  - platform: google_translate
    language: nl

frontend:
  themes: !include_dir_merge_named themes
  extra_module_url:
    - /local/card-mod.js

recorder:
  db_url: !secret db_url
  exclude:
    entities:
      - sensor.time
      - sensor.time_utc
      - sensor.date
      - sensor.date_time

discovery:

cloud:

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
cover: !include cover.yaml
#alarm_control_panel: !include alarm.yaml
camera: !include camera.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
notify: !include notify.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
media_player: !include media_players.yaml
light: !include lights.yaml
switch: !include switchs.yaml
proximity: !include proximities.yaml
scene: !include scenes.yaml
shell_command: !include shell_command.yaml
plant: !include plant.yaml
rest_command: !include rest_command.yaml
utility_meter: !include utility_meter.yaml
image_processing: !include image_processing.yaml
template: !include template.yaml
mqtt: !include mqtt.yaml

python_script:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id1
      - !secret telegram_bot_chat_id2

#vacuum:
#  - platform: xiaomi_miio
#    host: dalek.fritz.box
#    token: !secret xiaomi_vacuum_token

ifttt:
  key: !secret ifttt-key  

#zoneminder:
#  - host: !secret zoneminder-host
#    ssl: true
#    verify_ssl: false
#    username: !secret zoneminder-username
#    password: !secret zoneminder-password

stream:

downloader:
  download_dir: www

ramses_cc:
  serial_port: /dev/serial/by-id/usb-Texas_Instruments_TUSB3410_Boot_Device_TUSB3410-if00-port0
  restore_cache: true
  scan_interval: 60
  packet_log:
    file_name: /config/ramses_cc_packet.log
    rotate_bytes: null
    rotate_backups: 7
  ramses_rf:
    enable_eavesdrop: false
    enforce_known_list: true
  01:223036:
    system:
      appliance_control: 10:040239 
    zones:
      "00": {sensor: 01:223036}
  known_list:
    01:223036:                            # Evohome (Temperature control system)
    04:231770:
    04:231772:
    04:231774:
    04:231776:
    04:050559:
    04:155445:
    04:155403:
    04:081849:
    04:155443:
    04:155407:
    04:155551:
    04:155533:
    04:155537:
    10:040239:                            # OTB
    18:005567:                            # Honeywell HGI80

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  database: homeassistant
  username: !secret influxdb-username
  password: !secret influxdb-password
  max_retries: 3
  default_measurement: state