homeassistant:
  media_dirs:
    media: /media
    snapshots: /config/www/snapshots
    security: /config/www/security
  customize: !include customize.yaml
  auth_providers:
    - type: homeassistant
    - type: trusted_networks
      trusted_networks:
        - 192.168.0.0/24
        - fd00::/8

# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:

# Uncomment this if you are using SSL/TLS, running in Docker container, etc.
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.0.208

# Text to speech
tts:
  - platform: google_translate
    language: nl
    base_url: https://ha.delodder.be

frontend:
  themes: !include_dir_merge_named themes

recorder:
  db_url: !secret db_url
  exclude:
    entities:
      - sensor.time
      - sensor.time_utc
      - sensor.date
      - sensor.date_time

discovery:

cloud:

zone: !include zones.yaml
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
cover: !include cover.yaml
#alarm_control_panel: !include alarm.yaml
camera: !include camera.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
device_tracker: !include device_tracker.yaml
notify: !include notify.yaml
variable: !include variable.yaml
sensor: !include sensors.yaml
binary_sensor: !include binary_sensors.yaml
media_player: !include media_players.yaml
light: !include lights.yaml
switch: !include switchs.yaml
proximity: !include proximities.yaml
scene: !include scenes.yaml
shell_command: !include shell_command.yaml
plant: !include plant.yaml
rest_command: !include rest_command.yaml
utility_meter: !include utility_meter.yaml
image_processing: !include image_processing.yaml

python_script:

telegram_bot:
  - platform: polling
    api_key: !secret telegram_bot_api_key
    allowed_chat_ids:
      - !secret telegram_bot_chat_id1
      - !secret telegram_bot_chat_id2

vacuum:
  - platform: xiaomi_miio
    host: dalek.fritz.box
    token: !secret vacuum_xiaomi_token

ifttt:
  key: !secret ifttt-key  

influxdb:
  host: a0d7b954-influxdb
  port: 8086
  username: !secret influxdb-user
  password: !secret influxdb-password
  database: !secret influxdb-database
  max_retries: 3
  default_measurement: state

#zoneminder:
#  - host: !secret zoneminder-host
#    ssl: true
#    verify_ssl: false
#    username: !secret zoneminder-username
#    password: !secret zoneminder-password

stream:

downloader:
  download_dir: www
  
shelly:
  devices:
    - id: "8AD925"
      light_switch: true
    - id: "8B191F"
      light_switch: true
    - id: "2BE5AF"
      light_switch: true
    - id: "2BD8B9"
      light_switch: true
    - id: "9F5B66"
      light_switch: true
    - id: "00C928"
      light_switch: true
    - id: "2C6E97"
      light_switch: true
      sensors: [ switch ]
    - id: "98F4ABD0C5D0"
      light_switch: true

spotify:
  client_id: !secret spotify-clientid
  client_secret: !secret spotify-client_secret
  
cast:
  media_player:

browser_mod:

google:
  client_id: !secret google-client_id
  client_secret: !secret google-client_secret