- platform: doods
  scan_interval: 10000
  url: "http://192.168.0.207:8080"
  detector: tensorflow
  source:
    - entity_id: camera.oprit
  file_out:
    - "/config/www/snapshots/{{ camera_entity.split('.')[1] }}_latest.jpg"
    - "/config/www/security/{{ camera_entity.split('.')[1] }}_{{ '%02d' % (states('input_number.oprit_last_cctv_motion_event') |int (0) ) }}_{{ now().strftime('%Y%m%d_%H%M%S') }}.jpg"
  labels:
    - name: person
      confidence: 30
    - name: car
      confidence: 30
    - name: truck

- platform: platerecognizer
  scan_interval: 10000
  api_token: !secret platerecognizer_apikey
  regions:
    - be
  save_file_folder: "/config/www/snapshots/platerecognizer"
  save_timestamped_file: True
  always_save_latest_file: True
  source:
    - entity_id: camera.doods_oprit

- platform: sighthound
  scan_interval: 10000
  api_key: !secret sighthound_apikey
  save_file_folder: "/config/www/snapshots/sighthound"
  save_timestamped_file: True
  source:
    - entity_id: camera.doods_oprit