- platform: group
  name: gelijkvloers group
  entities:
    - light.wc_beneden
    - light.inkom
    - light.schouw
    - light.staande_lamp_living

- platform: group
  name: eerste verdiep group
  entities:
    - light.slaapkamer_margot
    - light.nachttafel_margot
    - light.febe_slaapkamer
    - light.nachttafel_febe
    - light.febe_led_bed
    - light.dressing_spots
    - light.dressing_led_strip
    - light.gang_eerste_verdiep
    - light.shelly_dimmer_d0f117_light_0
    - light.wc_boven
    - light.led_slaapkamer

- platform: group
  name: Febe LEDs
  entities:
    - light.nachttafel_febe
    - light.febe_led_bed

- platform: group
  name: buiten group
  entities: 
    - light.voordeur
    - light.achterdeur
    - light.garage_buiten

- platform: group
  name: zolder group
  entities:
    - light.gang_zolder
    - light.speelkamer
    - light.led_speelkamer
    - light.bureau
    - light.geometric_lamp_2
    - light.cell_structure_lamp