- platform: group
  name: gelijkvloers
  entities:
    - light.wc_beneden
    - light.inkom
    - light.led_schouw
    - light.staande_lamp_living

- platform: group
  name: eerste verdiep 
  entities:
    - light.slaapkamer_margot
    - light.slaapkamer_febe
    - light.logeerkamer
    - light.gang_eerste_verdiep
    - light.wc_boven
    - light.led_slaapkamer

- platform: group
  name: buiten
  entities: 
    - light.voordeur
    - light.achterdeur
    - light.garage_buiten

- platform: group
  name: zolder
  entities:
    - light.gang_zolder
    - light.speelkamer
    - light.led_speelkamer
    - light.bureau
    - light.led_bureau
    - light.geometric_lamp_2
    - light.cell_structure_lamp
