- platform: switch
  name: Kerstboom
  entity_id: switch.kerstboom

- platform: switch
  name: Voortuin
  entity_id: switch.verlichting_buiten_voorkant

- platform: group
  name: Gelijkvloers
  entities:
    - light.wc_beneden
    - light.inkom
    - light.schouw
    - light.staande_lamp_living
    - light.led_mini_kerstboom_led
    - light.kerstboom
    - light.lamp_barkast
    - light.led_stars_light_led

- platform: group
  name: Eerste Verdiep
  entities:
    - light.slaapkamer_margot
    - light.margot_led_bed
    - light.febe_slaapkamer
    - light.febe_led_bed
    - light.dressing_spots
    - light.dressing_led_strip
    - light.gang_eerste_verdiep
    - light.wc_boven
    - light.led_slaapkamer

- platform: group
  name: Buiten
  entities: 
    - light.voordeur
    - light.achterdeur
    - light.garage_buiten
    - light.voortuin
    - light.rozenboom
    - light.verlichting_garage_voorkant
    - light.verlichting_garage_zijkant

- platform: group
  name: Zolder
  entities:
    - light.gang_zolder
    - light.speelkamer
    - light.bureau
    - light.desk_lamp
    - light.wled_speelkamer
    - light.wled_matrix
    - light.bureau_spot

- platform: group
  name: Garage
  entities:
    - light.verlichting_garage_gelijkvloers
    - light.verlichting_garage_zolder