- platform: switch
  name: Kerstboom
  entity_id: switch.kerstboom

- platform: switch
  name: Voortuin
  entity_id: switch.verlichting_buiten_voorkant

- platform: group
  name: Gelijkvloers
  entities:
    - light.wc_beneden
    - light.inkom
    - light.schouw
    - light.staande_lamp_living
    - light.kerst_vaas
    - light.led_mini_kerstboom_led
    - light.kerstboom

- platform: group
  name: Eerste Verdiep
  entities:
    - light.slaapkamer_margot
    - light.nachttafel_margot
    - light.febe_slaapkamer
    - light.nachttafel_febe
    - light.febe_led_bed
    - light.dressing_spots
    - light.dressing_led_strip
    - light.gang_eerste_verdiep
    - light.wc_boven
    - light.led_slaapkamer

- platform: group
  name: Febe LEDs
  entities:
    - light.nachttafel_febe
    - light.febe_led_bed

- platform: group
  name: Buiten
  entities: 
    - light.voordeur
    - light.achterdeur
    - light.garage_buiten
    - light.voortuin

- platform: group
  name: Zolder
  entities:
    - light.gang_zolder
    - light.speelkamer
    - light.bureau
    - light.desk_lamp
    - light.plank
    - light.wled_speelkamer
    - light.wled_matrix