#- platform: spotify
#  client_id: !secret spotify-clientid
#  client_secret: !secret spotify-client_secret
- platform: snapcast
  host: 192.168.0.24
- platform: mpd
  host: 192.168.0.24
  name: Huis
- platform: mpd
  host: 192.168.0.20
  name: Woonkamer
- platform: mpd
  host: 192.168.0.25
  name: Bureau