binary_sensor:
  - name: "Oprit CCTV Motion"
    state_topic: "cctv/oprit/motion"
    device_class: motion
    json_attributes_topic: "cctv/oprit/motion"
    value_template: '{{ value_json.motion }}'
    payload_off: "off"
    payload_on: "on"

sensor:
  - name: "Water Pump Flow Rate"
    unit_of_measurement: "L/h"
    state_topic: "smarthouse/water/flow-meter/1"
    value_template: "{{ value_json.mL_per_min * 0.06 }}"
    icon: mdi:water-pump