binary_sensor:
  - name: "Oprit CCTV Motion"
    state_topic: "cctv/oprit/motion"
    device_class: motion
    json_attributes_topic: "cctv/oprit/motion"
    value_template: '{{ value_json.motion }}'
    payload_off: "off"
    payload_on: "on"