create_sensor:
  name: Create a Zone sensor
  description: >-
    Create an emulated temperature sensor for a zone. Once created, it will immediately
    enter bind mode and respond appropriately to any controller. The controller must be
    listening for a sensor before calling this service (as per the normal bind process).

set_zone_temp:
  name: Set a Zone's temperature
  description: >-
    Announce the current temperature of a Zone's temperature sensor. The zone must have
    an emulated sensor (see the `create_zone_sensor` service call).
  fields:
    entity_id:
      description: The entity_id of the Zone.
      example: climate.main_room
    temperature:
      description: The current temperature in degrees Celsius.
      example: 21.3

reset_dhw_mode:
  name: Reset the DHW mode
  description: Reset the operating mode of the DHW controller.
  fields:
    entity_id:
      description: The entity_id of the water_heater.
      example: water_heater.stored_hw

set_dhw_boost:
  name: Set DHW boost mode
  description: Enable the DHW controller for an hour.
  fields:
    entity_id:
      description: The entity_id of the water_heater.
      example: water_heater.stored_hw

set_dhw_mode:
  name: Set the DHW mode
  description: >-
    Set the operating mode of the DHW controller, optionally for a given duration.
  target:
    integration: evohome_cc
    domain: water_heater
  fields:
    # entity_id:
    #   name: Entity ID
    #   description: The entity_id of the water_heater.
    #   example: water_heater.stored_hw
    mode:
      name: DHW mode
      description: >-
        The duration of the override. Optional, one of: follow_schedule,
        temporary_override or permanent_override.
      example: temporary_override
      selector:
        select:
          options:
            - follow_schedule
            - permanent_override
            - temporary_override
    active:
      name: DHW state
      description: >-
        The state of the water heater.
      selector:
        boolean:
      example: true
    duration:
      name: Override duration
      description: >-
        The duration of the override. Mutually exclusive with until.
      example: '{"minutes": 135}'
      selector:
        number:
          min: 15
          max: 1440
          step: 15
          unit_of_measurement: mins
          mode: slider
    until:
      name: Override end time
      description: >-
        The end of the override. Mutually exclusive with duration.
      example: '"YYYY-MM-DD HH:MM:SS"'

reset_dhw_params:
  name: Reset the DHW config
  description: Reset the configuration of the DHW controller.
  fields:
    entity_id:
      description: The entity_id of the water_heater.
      example: water_heater.stored_hw

set_dhw_params:
  name: Set the DHW config
  description: Set the configuration of the DHW controller.
  fields:
    entity_id:
      description: The entity_id of the water_heater.
      example: water_heater.stored_hw
    setpoint:
      description: >-
        The target temperature in degrees Celsius. Default is 50.0.
      example: 50.0
    overrun:
      description: >-
        The overrun in minutes. Default is 5.
      example: 5
    differential:
      description: >-
        The differential in degrees Celsius.  Default is 1.
      example: 1

refresh_system:
  name: Refresh the System
  description: >-
    Update the system state now, without waiting for the next scheduled update.

reset_system_mode:
  name: Fully reset the System
  description: >-
    The System will be in auto mode and all Zones will be in follow_schedule mode,
    including (if supported) those in permanent_override mode.

set_system_mode:
  name: Set the System
  description: >-
    The System will be in the new mode and all Zones not in permanent_override mode
    will be affected.
  fields:
    mode:
      description: "One of: auto, eco_boost, away, day_off, heat_off, or custom."
      example: away
    period:
      description: >-
        Optional. A period of time in days; used only with away, day_off, or custom. The
        system will revert to auto at midnight (up to 99 days, today is day 1).
      example: '{"days": 28}'
    duration:
      description: >-
        Optional. The duration in hours; used only with eco_boost (up to 24 hours).
      example: '{"hours": 18}'

reset_zone_config:
  name: Reset a Zone's config
  description: Reset the configuration of the Zone.
  fields:
    entity_id:
      description: The entity_id of the Zone.
      example: climate.bedroom

reset_zone_mode:
  name: Reset a Zone's mode
  description: Reset the operating mode of the Zone.
  fields:
    entity_id:
      description: The entity_id of the Zone.
      example: climate.bedroom

set_zone_config:
  name: Reset a Zone's config
  description: Reset the configuration of the Zone.
  fields:
    entity_id:
      description: The entity_id of the Zone.
      example: climate.bedroom
    min_temp:
      description: The minimum permitted setpoint (5-21, in degrees C).
      example: 5
    max_temp:
      description: The maximum permitted setpoint (21-35, in degrees C).
      example: 30

set_zone_mode:
  name: Set a Zone's mode
  description: >-
    Set the operating mode of the Zone, either indefinitely or for a given duration.
  fields:
    entity_id:
      description: The entity_id of the Zone.
      example: climate.bedroom
    mode:
      description: >-
        The duration of the override. Optional, one of: follow_schedule,
        advanced_override, temporary_override or permanent_override.
      example: temporary_override
    setpoint:
      description: >-
        The target temperature in degrees Celsius. Default is 21.0.
      example: 21.0
    duration:
      description: >-
        The duration of the override. Mutually exclusive with until.
      example: '{"minutes": 135}'
    until:
      description: >-
        The end of the override. Mutually exclusive with duration.
      example: '"YYYY-MM-DD HH:MM:SS"'

send_packet:
  name: Send a Packet
  description: Send a completely bespoke command packet.
  fields:
    device_id:
      description: The destination device_id.
      example: 01:123456
    verb:
      description: 'The packet verb, one of: I, RQ, RP, W.'
      example: RQ
    code:
      description: The packet code (class).
      example: 1F09
    payload:
      description: The packet payload as a hexadecimal string.
      example: '00'
