---
<<: !include sensor.yaml
<<: !include switch.yaml

output:
  - platform: gpio
    pin: GPIO4
    id: gpio_4

light:
  - platform: binary
    name: "${short_name}"
    output: gpio_4
    id: lightid

binary_sensor:
  - !include binary_sensor/status.yaml
  - platform: gpio
    pin:
      number: GPIO5
      # mode: INPUT_PULLUP
      # inverted: True
    name: "Switch ${name}"
    on_state:
      then:
        - light.toggle: lightid
    internal: true
    id: switchid
