substitutions:
  device: greenhouse_ble_beacon
  name: Greenhouse BLE Beacon
  update_interval: 10min
esphome:
  name: ${device}
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  domain: !secret lan_domain
  
  ap:
    ssid: "Greenhouse Ble Beacon"
    password: "VCGOdpeSTRJH"

logger:

api:
  reboot_timeout: 0s
<<: !include common/ota.yaml
<<: !include common/web_server.yaml
<<: !include common/text_sensors.yaml
<<: !include common/binary_sensor.yaml
<<: !include common/switch.yaml

esp32_ble_tracker:

sensor:
  - !include common/sensor/wifi-signal.yaml
  - !include common/sensor/uptime.yaml
  - platform: xiaomi_hhccjcy01
    mac_address: 80:EA:CA:89:02:74
    temperature:
      name: "Greenhouse Zone 1 Temperature"
    moisture:
      name: "Greenhouse Zone 1 Moisture"
    illuminance:
      name: "Greenhouse Zone 1 Illuminance"
    conductivity:
      name: "Greenhouse Zone 1 Soil Conductivity"
  - platform: xiaomi_hhccjcy01
    mac_address: 80:EA:CA:89:0E:95
    temperature:
      name: "Greenhouse Zone 2 Temperature"
    moisture:
      name: "Greenhouse Zone 2 Moisture"
    illuminance:
      name: "Greenhouse Zone 2 Illuminance"
    conductivity:
      name: "Greenhouse Zone 2 Soil Conductivity"
  - platform: xiaomi_hhccjcy01
    mac_address: 80:EA:CA:89:0E:A2
    temperature:
      name: "Greenhouse Zone 3 Temperature"
    moisture:
      name: "Greenhouse Zone 3 Moisture"
    illuminance:
      name: "Greenhouse Zone 3 Illuminance"
    conductivity:
      name: "Greenhouse Zone 3 Soil Conductivity"
  - platform: xiaomi_hhccjcy01
    mac_address: 80:EA:CA:89:09:DC
    temperature:
      name: "Greenhouse Zone 4 Temperature"
    moisture:
      name: "Greenhouse Zone 4 Moisture"
    illuminance:
      name: "Greenhouse Zone 4 Illuminance"
    conductivity:
      name: "Greenhouse Zone 4 Soil Conductivity"
    