homeassistant: true
mqtt:
  server: mqtt://core-mosquitto:1883
  user: mqtt
  password: JnWnYbC2hCr9PH
serial:
  port: >-
    /dev/serial/by-id/usb-Silicon_Labs_Sonoff_Zigbee_3.0_USB_Dongle_Plus_0001-if00-port0
frontend:
  port: 8099
advanced:
  homeassistant_legacy_entity_attributes: false
  legacy_api: false
  legacy_availability_payload: false
  log_syslog:
    app_name: Zigbee2MQTT
    eol: /n
    host: localhost
    localhost: localhost
    path: /dev/log
    pid: process.pid
    port: 123
    protocol: tcp4
    type: '5424'
  transmit_power: 9
  channel: 25
  last_seen: ISO_8601_local
  network_key:
    - 191
    - 5
    - 185
    - 242
    - 79
    - 202
    - 131
    - 105
    - 253
    - 3
    - 88
    - 249
    - 141
    - 224
    - 201
    - 166
  pan_id: 55593
  log_level: warn
device_options:
  legacy: false
availability: true
devices:
  '0x000d6ffffee41a9d':
    friendly_name: Laptop Outlet
  '0x00158d000358207c':
    friendly_name: Motion Bureau
  '0x00158d000272bb18':
    friendly_name: Motion Gang Zolder
  '0x00158d0003f47876':
    friendly_name: Motion Speelkamer
  '0x00158d0004253f52':
    friendly_name: Temperature Bureau
  '0xec1bbdfffe8d6cac':
    friendly_name: Temperature Gang Eerste
  '0x588e81fffe5f73de':
    friendly_name: Motion WC Boven
  '0x000d6ffffe557c23':
    friendly_name: Staande Lamp Living
  '0x680ae2fffee9d570':
    friendly_name: Lamp Barkast
  '0x588e81fffeff5e81':
    friendly_name: Droogkast
    measurement_poll_interval: 2
  '0x842e14fffe366881':
    friendly_name: Wasmachine
    measurement_poll_interval: 2
  '0x842e14fffe139511':
    friendly_name: Koelkast/Vriezer Berging
    measurement_poll_interval: 2
  '0x003c84fffe8c9c0e':
    friendly_name: Brander
    measurement_poll_interval: 2
  '0x842e14fffe36688c':
    friendly_name: Boiler Keuken
    measurement_poll_interval: 2
  '0x84ba20fffe7c2569':
    friendly_name: Vaatwas
    measurement_poll_interval: 2
  '0x842e14fffe1265b6':
    friendly_name: Koelkast Keuken
    measurement_poll_interval: 2
  '0x842e14fffef25906':
    friendly_name: Waterpomp
    measurement_poll_interval: 1
  '0x842e14fffe13929f':
    friendly_name: Vriezer Garage
    measurement_poll_interval: 2
  '0x842e14fffe359de1':
    friendly_name: Koelkast/Vriezer Garage
    measurement_poll_interval: 2
  '0x84fd27fffece97d4':
    friendly_name: Computer
    power_calibration: 0
  '0x00158d000173f38e':
    friendly_name: Dressing Ledstrip
  '0xccccccfffeaa677b':
    friendly_name: Dressing Spot 1
  '0x680ae2fffeea5c13':
    friendly_name: Dressing Spot 2
  '0x680ae2fffeef6f0f':
    friendly_name: Dressing Spot 3
  '0x680ae2fffeea4e7f':
    friendly_name: Dressing Spot 4
  '0x00158d000200e19d':
    friendly_name: Motion Woonkamer
  '0x00158d0002090933':
    friendly_name: Achterdeur
  '0x00158d000200d19f':
    friendly_name: Motion Keuken
  '0x54ef4410004cdf22':
    friendly_name: Keukendeur
  '0x00158d00044494b8':
    friendly_name: 'Temperature Achterdeur Buiten '
  '0x54ef4410004cd327':
    friendly_name: Garagedeur
  '0x001788010bcef3cc':
    friendly_name: Motion WC Beneden
  '0x00158d000273b976':
    friendly_name: Voordeur
  '0x001788010949d9cb':
    friendly_name: Motion Voordeur
  '0x7cb03eaa0a009f3f':
    friendly_name: Verlichting Buiten Voorkant
  '0x00158d0003faeed6':
    friendly_name: Motion Inkom 1
  '0x00158d0004057149':
    friendly_name: Motion Inkom 2
  '0x00178801086c42a8':
    friendly_name: Slaapkamer Dimmer Switch
  '0x000000000171d428':
    friendly_name: Dressing Switch
  '0x00158d0004f9722c':
    friendly_name: Slaapkamer Febe Spot Bureau 2
  '0x00158d0004f9558d':
    friendly_name: Slaapkamer Febe Spot Gang
  '0x00158d0004f95651':
    friendly_name: Slaapkamer Febe Spot Kleerkast 2
  '0x00158d0004c40c62':
    friendly_name: Slaapkamer Febe Spot Spiegel
  '0x00158d0004f98b23':
    friendly_name: Slaapkamer Febe Spot Bureau 1
  '0x00158d0004c30d0f':
    friendly_name: Slaapkamer Febe Spot Kleerkast 1
  '0x000000000171b6c9':
    friendly_name: Slaapkamer Febe Switch
  '0x00158d0004467811':
    friendly_name: Slaapkamer Febe Button Spots
  '0x00158d000290783e':
    friendly_name: Slaapkamer Febe Button Led
  '0x0017880109182ad1':
    friendly_name: Motion Gang Eerste 2
  '0x001788010918206e':
    friendly_name: Motion Gang Eerste 1
  '0x086bd7fffee97bb7':
    friendly_name: Motion Dressing
  '0x001788010bd16fac':
    friendly_name: Motion Garagepoort
  '0x00158d0001e83345':
    friendly_name: Garagepoort Button
  '0x0c4314fffe4ac2ac':
    friendly_name: Woonkamer Scene 5 Button
  '0x000d6ffffe50499e':
    friendly_name: Staande Lamp 5 Button
  '0xec1bbdfffedf6ba3':
    friendly_name: Temperature Serre
  '0x94deb8fffe10f89b':
    friendly_name: Slaapkamer Margot Spot Bureau 1
  '0x84ba20fffe9be0ae':
    friendly_name: Slaapkamer Margot Spot Bureau 2
  '0x94deb8fffe110464':
    friendly_name: Slaapkamer Margot Spot Kleerkast 2
  '0x84ba20fffea0e2c0':
    friendly_name: Slaapkamer Margot Spot Kleerkast 1
  '0x003c84fffe636842':
    friendly_name: Slaapkamer Margot Spot Spiegel
  '0x0000000001740fa3':
    friendly_name: Slaapkamer Margot Switch
  '0x00158d000446780b':
    friendly_name: Slaapkamer Margot Button Led
  '0x003c84fffe17d359':
    friendly_name: Slaapkamer Margot Toggle Spots
  '0x000d6ffffeaac6a7':
    friendly_name: 'Woonkamer Toggle Button '
  '0xa4c138b5c299ceb4':
    friendly_name: Brievenbus In
  '0x00124b0029119349':
    friendly_name: Temperature Buitenkast
  '0xa4c1381c24a3ce9c':
    friendly_name: Kerstboom
  '0xa4c13876a95a3462':
    friendly_name: Haag Straat
groups:
  '1':
    friendly_name: Dressing Spots
    devices:
      - 0xccccccfffeaa677b/1
      - 0x680ae2fffeea5c13/1
      - 0x680ae2fffeef6f0f/1
      - 0x680ae2fffeea4e7f/1
  '2':
    friendly_name: Slaapkamer Febe Spots
    devices:
      - 0x00158d0004f98b23/1
      - 0x00158d0004f9722c/1
      - 0x00158d0004f9558d/1
      - 0x00158d0004c30d0f/1
      - 0x00158d0004f95651/1
      - 0x00158d0004c40c62/1
  '3':
    friendly_name: Slaapkamer Febe Spots Kleerkast
    devices:
      - 0x00158d0004c30d0f/1
      - 0x00158d0004f95651/1
  '4':
    friendly_name: Slaapkamer Febe Spots Bureau
    devices:
      - 0x00158d0004f98b23/1
      - 0x00158d0004f9722c/1
  '5':
    friendly_name: Slaapkamer Margot Spots
    devices:
      - 0x94deb8fffe10f89b/1
      - 0x84ba20fffe9be0ae/1
      - 0x84ba20fffea0e2c0/1
      - 0x94deb8fffe110464/1
      - 0x003c84fffe636842/1
  '6':
    friendly_name: Slaapkamer Margot Spots Kleerkast
    devices:
      - 0x84ba20fffea0e2c0/1
      - 0x94deb8fffe110464/1
  '7':
    friendly_name: Slaapkamer Margot Spots Bureau
    devices:
      - 0x94deb8fffe10f89b/1
      - 0x84ba20fffe9be0ae/1
